# Hosts Configuration
hosts:
  - size: [5]                      # Se crearán 10 hosts
    heterogeneous: true             # Los hosts son heterogéneos
    ram: [8192]              # RAM fija de 8192Mb
    storage: [200000]        # Almacenamiento fijo de 200000 MB
    bw: [5000]                      # Ancho de banda fijo en 5000 Mbps
    pesNumber: [4]               # PEs 4
    mips: [15000]            # MIPS fijos de 15000
    vmScheduler: 0                  # Política de VM: TimeShared
