# Hosts Configuration
# hosts:
#   - size: [5]                       # Se crearán 10 hosts
#     pesNumber: [32]     #32Pe       # PEs 4
#     ram: [65536]        #64GB       # RAM fija de 8192Mb
#     storage: [2048000]  #2TB        # Almacenamiento fijo de 200000 MB
#     bw: [512]           #5GB        # Ancho de banda fijo en 5000 Mbps
#     mips: [2000]                    # MIPS fijos de 15000
#     vmScheduler: 0                  # Política de VM: SpaceShared
#     heterogeneous: true             # Los hosts son heterogéneos
hosts:
  - size: [1]                       # Se crearán 10 hosts
    pesNumber: [100000]     #32Pe       # PEs 4
    ram: [100000]        #64GB       # RAM fija de 8192Mb
    storage: [100000]  #2TB        # Almacenamiento fijo de 200000 MB
    bw: [100000]           #5GB        # Ancho de banda fijo en 5000 Mbps
    mips: [100000]                    # MIPS fijos de 15000
    vmScheduler: 1                 # Política de VM: SpaceShared
    heterogeneous: true             # Los hosts son heterogéneos
