#
tasks:
  size: [10]                 # Se generarán 50 tareas fijas
  pesNumber: [3]              # PEs fijos
  length: [10,1000]               # Longitud de tarea fija de 10000 MI
  fileSize: [200]             # Tamaño de archivo fijo en 1000 MB
  outputSize: [200]           # Tamaño de salida fijo de 500 MB
  heterogeneous: True        # Las tareas son homogéneas
