# VMs Configuration
vms:
  - size: [1]             # Se crearán 5 VMs
    pesNumber: [2,8]            # 2 PEs fijos
    mips: [200]                      # 1000 MIPS fijos
    ram: [2048,16384]                     # RAM fija de 2048 MB
    storage: [100000]                # Almacenamiento fijo de 10000 MB
    bw: [512]                      # Ancho de banda fijo de 1000 Mbps
    taskScheduler: 1                # Política de tareas: TimeShared
    heterogeneous: false            # Las VMs son homogéneas
