# Datacenter Costs
costPerSec: 0.05
costPerMem: 0.01
costPerStorage: 0.001
costPerBw: 0.002

# Hosts Configuration
hosts:
  size: [1]                       # Se crearán 10 hosts
  pesNumber: [100000] #32Pe       # PEs 4
  ram: [100000]       #64GB       # RAM fija de 8192Mb
  storage: [100000]   #2TB        # Almacenamiento fijo de 200000 MB
  bw: [100000]        #5GB        # Ancho de banda fijo en 5000 Mbps
  mips: [100000]                  # MIPS fijos de 15000
  vmScheduler: 1                  # Política de VM: SpaceShared
  heterogeneous: true             # Los hosts son heterogéneos


# VMs Configuration
vms:
  seed: 10
  size: [1]                       # Se crearán 5 VMs
  pesNumber: [2,8]                # 2 PEs fijos
  mips: [200]                     # 1000 MIPS fijos
  ram: [2048,16384]               # RAM fija de 2048 MB
  storage: [100000]               # Almacenamiento fijo de 10000 MB
  bw: [512]                       # Ancho de banda fijo de 1000 Mbps
  taskScheduler: 1                # Política de tareas: TimeShared
  heterogeneous: false            # Las VMs son homogéneas

# Tasks Configuration (Cloudlets)
tasks:
  seed: 10
  size: [10]                      # Se generarán 50 tareas fijas
  pesNumber: [3]                  # PEs fijos
  length: [10,1000]               # Longitud de tarea fija de 10000 MI
  fileSize: [200]                 # Tamaño de archivo fijo en 1000 MB
  outputSize: [200]               # Tamaño de salida fijo de 500 MB
  heterogeneous: True             # Las tareas son homogéneas


#1- Hacer tareas que duren de manera aleatoria diferente tiempo
#2- Hacer el escenario secuencial
#4- Ver si se pueden construir los escenarios que hizo el otro grupo.